# -*- coding: utf-8 -*-
"""augmentasii

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KIOdo1vrmx9yN5G-ORiCsovd2Wl05QsT
"""

pip install imgaug

# Mount Google Drive
from google.colab import drive
drive.mount('/content/gdrive')

import os
COLAB_PATH = "gdrive/MyDrive/dataset/buah kersen"
os.chdir(COLAB_PATH)

import os
import cv2
import imgaug as ia
from imgaug import augmenters as iaa

# Membuat objek augmentor
augmentor = iaa.Sequential([
    iaa.Fliplr(0.5),  # Flipping secara horizontal
    iaa.Affine(rotate=(-180, 180)),  # Rotasi gambar antara -10 dan 10 derajat
    iaa.GaussianBlur(sigma=(0, 1.0)),  # Blur gambar dengan sigma antara 0 dan 1.0
    iaa.AdditiveGaussianNoise(scale=(0, 0.1 * 255))  # Tambahkan Gaussian noise dengan skala antara 0 dan 0.1
])

# Path ke direktori gambar asli
original_images_dir = './original'
# Path ke direktori untuk menyimpan gambar yang sudah di-augmentasi
augmented_images_dir = './augmentasi'

# Membuat direktori untuk menyimpan gambar yang sudah di-augmentasi jika belum ada
os.makedirs(augmented_images_dir, exist_ok=True)

# Daftar semua nama gambar asli di direktori
image_files = os.listdir(original_images_dir)

# Jumlah data augmentasi yang diinginkan
desired_num_augmented = 200

# Augmentasi dan menyimpan setiap gambar hingga mencapai jumlah data yang diinginkan
for image_file in image_files:
    # Membaca gambar asli
    image_path = os.path.join(original_images_dir, image_file)
    image = cv2.imread(image_path)

    # Melakukan augmentasi pada gambar hingga mencapai jumlah data yang diinginkan
    num_augmented = 0
    while num_augmented < desired_num_augmented:
        augmented_images = augmentor(images=[image])

        # Menyimpan semua gambar yang sudah di-augmentasi
        for i, augmented_image in enumerate(augmented_images):
            augmented_image_path = os.path.join(augmented_images_dir, f"augmented_{num_augmented}_{image_file}")
            cv2.imwrite(augmented_image_path, augmented_image)
            num_augmented += 1

            if num_augmented >= desired_num_augmented:
                break

        if num_augmented >= desired_num_augmented:
            break