# -*- coding: utf-8 -*-
"""segmentasi daun eceng gondok

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rCgKL72D15HkVtGnbe4nT7DRnmZmPGkX
"""

!nvidia-smi

#check gpu
import torch

torch.cuda.is_available()

import os
HOME = os.getcwd()
print(HOME)

# Pip install method (recommended)

!pip install ultralytics==8.0.134

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="FznPOLhlJ9aCCPE8N2Jp")
project = rf.workspace("universitas-widyagama-malang-k0sna").project("leaf-eceng-gondok")
dataset = project.version(1).download("yolov8")

"""training data"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=segment mode=train model=yolov8s-seg.pt data={dataset.location}/data.yaml epochs=100 imgsz=640

!ls {HOME}/runs/segment/train/

!pip install Pillow

from IPython.display import Image

Image(filename=f'{HOME}/runs/segment/train/confusion_matrix.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/segment/train/results.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/segment/train/val_batch0_pred.jpg', width=600)

"""Testing model"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=segment mode=val model={HOME}/runs/segment/train/weights/best.pt data={dataset.location}/data.yaml

"""Inference with Custom Model"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=segment mode=predict model={HOME}/runs/segment/train/weights/best.pt conf=0.25 source={dataset.location}/test/images

import glob
from IPython.display import Image, display

image_paths = glob.glob(f'{HOME}/runs/segment/predict/*.jpg')

for image_path in image_paths[:15]:
    display(Image(filename=image_path, height=600))

# Commented out IPython magic to ensure Python compatibility.
#see the accuracie
# %load_ext tensorboard
# %tensorboard --logdir runs/segment/train2

from google.colab import files
import pandas as pd
result.to_csv('example_file.csv')
files.download('example_file.csv')

!git --version

!git init